### ISSUE TITLE
Add CSS base_url 

### ISSUE THREAD

**Issue by wolfv** [upfrontIO/livingdocs-engine#121]
If the livingdocs engine resides in a non-default folder, the css is not loaded because the path is not correct.
Adding a base_url variable that is prepended to the resulting path would make that easier.

E.g. I am trying to use it in a flask application, where the base_url should be `js/vendor/livingdocs-engine/public`

Would be a cool addition to the config variables.

**Comment by marcbachmann** [comment]
I believe this is fixed. Please reopen the issue or create a new if there's still an issue with assets.
